---
openapi: 3.0.3
info:
  title: onecx-chat chats import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/chat:
    post:
      operationId: importChat
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  schemas:
    ChatType:
      type: string
      enum:
        - HUMAN_CHAT
        - AI_CHAT
    MessageType:
      type: string
      enum:
        - HUMAN
        - ASSISTANT
        - SYSTEM
    DataImport:
      type: object
      properties:
        chats:
          $ref: '#/components/schemas/DataImportChats'
    DataImportChats:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportChat'
    DataImportChat:
      type: object
      required:
        - tenantId
      properties:
        tenantId:
          type: string
        type:
          $ref: '#/components/schemas/ChatType'
        topic:
          type: string
        summary:
          type: string
        appId:
          type: string
